# Generated by Django 5.1.2 on 2024-10-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_orderitem_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_price',
            new_name='price',
        ),
    ]
