# Generated by Django 5.1.2 on 2024-10-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Необработанный'), ('prc', 'Готовится'), ('del', 'В доставке'), ('com', 'Завершен')], db_index=True, default='new', max_length=3, verbose_name='Статус заказа'),
        ),
    ]
