# Generated by Django 5.1.2 on 2024-10-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_order_called_at_order_delivered_at_order_register_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'По карте'), ('cash', 'Наличные')], db_index=True, default='По карте', verbose_name='Способ оплаты'),
        ),
    ]
