# Generated by Django 5.1.2 on 2024-10-29 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_orderitem_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant'),
        ),
    ]
