# Generated by Django 5.1.2 on 2024-11-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'По карте'), ('cash', 'Наличные')], db_index=True, default='По карте', verbose_name='Способ оплаты'),
        ),
    ]
