# Generated by Django 5.1.2 on 2024-10-30 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, unique=True, verbose_name='Адрес')),
                ('longitude', models.DecimalField(decimal_places=11, max_digits=13, verbose_name='Долгота')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=12, verbose_name='Широта')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
